spring.application.name=agendador-reunioes

# 1. Configuração de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/agendador_db
spring.datasource.username=admin
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configurações do JPA e Hibernate
# 'update' faz o Spring criar as tabelas no banco de dados automaticamente com base nas nossas @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Mostrar os comandos SQL no console (Ótimo para visualizar o que está acontecendo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true